version: '3.8'

services:
  fetch-service:
    build:
      context: .            
      dockerfile: Dockerfile
    image: fetch-service:latest
    container_name: fetch-service
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=info
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
